# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/

# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name (set in params.yaml under hugoblox.branding.name)
title: "Madimetja Reginald Maredi"

# Website URL
baseURL: 'https://researchmaredi.github.io/academic-portfolio/'  # Replace with your URL

############################################
## LOCALE
############################################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################################
## ADVANCED
############################################

build:
  writeStats: true
  enableGitInfo: false
  summaryLength: 30

pagination:
  pagesize: 10

enableEmoji: true
enableMissingTranslationPlaceholders: true
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableKinds: ["taxonomy", "term"]
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]